"""Add readiness_score to Project

Revision ID: bd8fb50b42cf
Revises: ca943bf72684
Create Date: 2026-08-18 11:51:26.356628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8fb50b42cf'
down_revision = 'ca943bf72684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readiness_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('readiness_score')

    # ### end Alembic commands ###
