"""Add audit_logs table

Revision ID: c53df49cd8f8
Revises: bd8fb50b42cf
Create Date: 2026-08-18 22:56:51.079966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53df49cd8f8'
down_revision = 'bd8fb50b42cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    user_columns = [c['name'] for c in inspector.get_columns('users')]

    if 'is_admin' not in user_columns:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True, server_default=sa.false()))

    if 'audit_logs' not in tables:
        op.create_table(
            'audit_logs',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('action', sa.String(length=128), nullable=False),
            sa.Column('resource_type', sa.String(length=64), nullable=True),
            sa.Column('resource_id', sa.String(length=128), nullable=True),
            sa.Column('status', sa.String(length=32), nullable=False, server_default='success'),
            sa.Column('details', sa.Text(), nullable=True),
            sa.Column('ip_address', sa.String(length=64), nullable=True),
            sa.Column('user_agent', sa.String(length=512), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('audit_logs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    user_columns = [c['name'] for c in inspector.get_columns('users')]

    if 'audit_logs' in tables:
        with op.batch_alter_table('audit_logs', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
            batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
            batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

        op.drop_table('audit_logs')

    if 'is_admin' in user_columns:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_column('is_admin')
    # ### end Alembic commands ###
