"""Add version_id for optimistic locking

Revision ID: ca943bf72684
Revises: 9c731bb7d38a
Create Date: 2026-08-18 11:39:41.301462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca943bf72684'
down_revision = '9c731bb7d38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('version_id')

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_column('version_id')

    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_column('version_id')

    # ### end Alembic commands ###
