import { useEffect, useState, useRef } from "react"
import { Link } from "react-router-dom"
import api from "../api"

const STATUS_META = {
  pending: { label: "Pending", cls: "bg-slate-500/20 text-slate-300", icon: "⏳" },
  provisioning: { label: "Provisioning", cls: "bg-blue-500/20 text-blue-300", icon: "🔄" },
  deploying: { label: "Deploying", cls: "bg-purple-500/20 text-purple-300", icon: "📦" },
  running: { label: "Running", cls: "bg-emerald-500/20 text-emerald-300", icon: "✅" },
  failed: { label: "Failed", cls: "bg-rose-500/20 text-rose-300", icon: "❌" },
  rolled_back: { label: "Rolled Back", cls: "bg-yellow-500/20 text-yellow-300", icon: "⏪" },
  success: { label: "Finished", cls: "bg-emerald-500/20 text-emerald-300", icon: "✅" }
}

const DeploymentMonitor = () => {
  const [deployments, setDeployments] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const pollRef = useRef(null)

  const fetchDeployments = async () => {
    try {
      const res = await api.get("/deploy/all")
      setDeployments(res.data.deployments || [])
      setError(null)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchDeployments()
    pollRef.current = setInterval(fetchDeployments, 3000)
    return () => clearInterval(pollRef.current)
  }, [])

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="h-7 w-7 animate-spin rounded-full border-2 border-indigo-500 border-t-transparent" />
      </div>
    )
  }

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="rounded-2xl border border-indigo-500/20 bg-indigo-500/5 p-8 relative overflow-hidden">
        <div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-indigo-500/10 blur-3xl" />
        <div className="absolute -left-10 -bottom-10 h-40 w-40 rounded-full bg-emerald-500/10 blur-3xl" />
        <h1 className="text-2xl font-bold text-white relative z-10">Deployment Monitor</h1>
        <p className="mt-2 text-indigo-200/70 relative z-10 max-w-2xl">
          Track live AWS EC2 deployments, inspect infrastructure health, and review automated rollbacks and incident reports generated by the monitoring engine.
        </p>
      </div>

      {error && (
        <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-6 text-sm text-rose-400">
          Failed to load deployments: {error}
        </div>
      )}

      {deployments.length === 0 && !error ? (
        <div className="rounded-xl border border-subtle bg-[#111827] p-12 text-center">
          <span className="text-4xl mb-4 block">🚀</span>
          <h2 className="text-lg font-semibold text-white">No deployments yet</h2>
          <p className="mt-2 text-sm text-slate-400">Deploy a project to see it tracked here.</p>
        </div>
      ) : (
        <div className="grid gap-4">
          {deployments.map((dep) => {
            const statusMeta = STATUS_META[dep.status] || STATUS_META.pending
            return (
              <div key={dep.id} className="rounded-xl border border-subtle bg-[#111827] p-6 transition-all hover:border-slate-700 relative overflow-hidden">
                {/* Visual indicator for rolled back state */}
                {dep.status === "rolled_back" && (
                  <div className="absolute top-0 left-0 w-1 h-full bg-yellow-500" />
                )}
                
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                  <div>
                    <div className="flex items-center gap-3">
                      <h2 className="text-lg font-semibold text-white">
                        Deployment #{dep.id}
                      </h2>
                      <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium ${statusMeta.cls}`}>
                        {statusMeta.icon} {statusMeta.label}
                      </span>
                    </div>
                    <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-slate-400">
                      <span className="flex items-center gap-1">
                        <span className="text-slate-500">Env:</span>
                        <span className="text-white capitalize">{dep.environment}</span>
                      </span>
                      {dep.instance_id && (
                        <span className="flex items-center gap-1">
                          <span className="text-slate-500">Target:</span>
                          <span className="font-mono text-indigo-300 bg-indigo-500/10 px-1.5 rounded">{dep.instance_id}</span>
                        </span>
                      )}
                      <span className="flex items-center gap-1">
                        <span className="text-slate-500">Started:</span>
                        {new Date(dep.deployed_at).toLocaleString()}
                      </span>
                    </div>
                  </div>

                  <div className="flex items-center gap-3">
                    <button className="rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-sm font-medium text-white hover:bg-white/10 transition-colors">
                      View Logs
                    </button>
                  </div>
                </div>

                {/* Incident Notice */}
                {dep.incident && (
                  <div className="mt-4 rounded-lg bg-rose-500/10 border border-rose-500/20 p-4">
                    <div className="flex gap-3">
                      <span className="text-rose-500">⚠️</span>
                      <div>
                        <h4 className="text-sm font-semibold text-rose-400">Incident Auto-Resolved</h4>
                        <p className="mt-1 text-sm text-rose-300/80">{dep.incident}</p>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

export default DeploymentMonitor
